### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by z-dump** [MaksimRudnev/ShinyValues#1]
Версия Rstudio последняя, выдало следующие ошибки:

Loading required package: ggrepel
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ggrepel’
Loading required package: stringr
Loading required package: sf
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘sf’
Warning: Error in : Aesthetics must be either length 1 or the same as the data (1): x, y, label

Warning: Error in geom_label_repel: could not find function "geom_label_repel"

Error in names(frame) <- `*vtmp*` : names() applied to a non-vector

Интерфейс открылся, кнопки нажимаются, но нажатие вызывает ошибки.
Может быть, конечно, ошибка с моей стороны, но ничего особого не делал.

![image](https://user-images.githubusercontent.com/26999980/43590342-0f3db0de-9671-11e8-995b-3b5f33142502.png)

**Comment by MaksimRudnev** [comment]
The first part of your errors points out that your machine doesn't have the required packages installed: 
ggrepel, stringr, and sf. Please note that the app is dependent on several packages and won't run wihout them. You can use to quickly install them the following line:

`install.packages(c("devtools", "shiny", "ggplot2", "ggrepel", "reshape2", "stringr", "maps", "sf", "readr"))`

I have updated the app to fix some encoding problems that appeared under Windows.

Please report if you have further problems.
